### ISSUE TITLE
Autozoom and Refresh

### ISSUE THREAD

**Issue by risturiz** [AntonKhorev/osm-note-viewer#2]
Hi, we was working with the app and have two additional questions:

- Map autozoom: ( it´s possible to zoom selected note?, this option work with "map area" using RC ) Actually if i select a Note + RC area the query is too big... So maybe zoom selected Note could solve this.
- Refresh by time: Fetch notes and don't want to move the map, refresh the fetched notes to update with actual filter ( something like Fetch notes on map view changes but without the need to change the view ). Ex: I fetch 100 notes and begin to solve them, the solved notes should disappear from the list with some auto refresh like 5min or 10min

Thanks again! :-)

**Comment by AntonKhorev** [comment]
> solved notes should disappear

Right now you can make them disappear. First, you can have a filter that shows only notes with a last action being something other than *closed*:

    action != closed
    $

Then you can close the note using some other app. Then you refresh the note by clicking its id in the table.

The drawbacks are:

- This refresh is not yet persisted in the browser's note database. If you reload the page, the old state of the note will reappear. You'll have to rerun the entire query and reload all the notes you want to see.
- Maybe you don't want to rerun the query because it was made by a bounding box and you already lost the bbox by moving the map around.
- You have to click on every note. Maybe that's too many notes or you don't want to look for them in the table.

I can add a button to refresh selected notes. I'm not sure if auto refresh by time is a good idea.

If you have a set of notes fetched and you want to work with exactly this set, you can switch to *Plaintext* tab and press *Copy note ids* button. Now if you fetch notes from this tab it's going to work like a refresh of all notes.

**Comment by AntonKhorev** [comment]
> Map autozoom

You say you "select a Note". If it's just one note that you see in the table, you can repeatedly click it and the map is going to zoom to it.

**Comment by risturiz** [comment]
> I can add a button to refresh selected notes. I'm not sure if auto refresh by time is a good idea.

Maybe refresh button could work ( like auto-refresh but manual )... So i can refresh Notes when other people are solving them in the same bbox ( like bbox some city, check only open, fetch notes and begin to work on them... I can solve the note on Josm and refresh the list to see what are available... Not the best option but help a lot when you work online with some team ).

> If you have a set of notes fetched and you want to work with exactly this set, you can switch to _Plaintext_ tab and press _Copy note ids_ button. Now if you fetch notes from this tab it's going to work like a refresh of all notes.

Ok, nice tip... I'm going to test this.

Thanks!

**Comment by risturiz** [comment]
> > Map autozoom
> 
> You say you "select a Note". If it's just one note that you see in the table, you can repeatedly click it and the map is going to zoom to it.

Yes but :-) ... Actually "Map autozoom" have: disable / to notes on screen in table / to all visible notes ... I see i can click two times on a Note to zoom, but an additional option "to selected notes" could save time when to check note->max zoom->josm rc

Thanks!

**Comment by risturiz** [comment]
> Added _Map autozoom_ > _to selected notes_

Works perfect! Thanks a lot!

**Comment by AntonKhorev** [comment]
I don't want autorefresh because I don't want notes to disappear without users doing anything. If there's a filter enabled, an updated note may no longer match the filter, then it has to be removed.

Maybe I'll add some indicator that the note was updated without displaying its new state automatically.

**Comment by risturiz** [comment]
> Maybe I'll add some indicator that the note was updated without displaying its new state automatically.

That could work too

**Comment by AntonKhorev** [comment]
Manual note updates are now saved to local db.

**Comment by AntonKhorev** [comment]
Added checking every five minutes if note was updated. There should be a growing progress indicator under the note id. Once it fills up, the check is made. If there was an update, a small circle appears above the id.

**Comment by risturiz** [comment]
This app it's getting better every day... Thanks a lot for your time
